hw4
Gani4ka/node-course1 pull request #4
Opened 2020-09-29 20:43 UTC by Gani4ka

2020-09-30 06:57 UTC, odykyi commented on middlewares/authorization.js
> +      jwt.decode(tokenRecord.token, "test");
jwt.verify

2020-09-30 06:57 UTC, odykyi requested changes
comments

2020-09-30 17:46 UTC, Gani4ka commented on middlewares/authorization.js
> +      jwt.decode(tokenRecord.token, "test");
done

2020-10-01 07:13 UTC, odykyi approved these changes

2020-10-01 07:13 UTC, merged